/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CacheComposeModel_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CacheComposeModel_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CacheComposeModel_request_H_


#include "c3dservice-api/ModelBase.h"

#include "c3dservice-api/model/ComposeModelNode.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ComposeModelNode;

/// <summary>
/// 
/// </summary>
class  CacheComposeModel_request
    : public ModelBase
{
public:
    CacheComposeModel_request();
    virtual ~CacheComposeModel_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CacheComposeModel_request members

    /// <summary>
    /// UUID to assign model
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ComposeModelNode> getRoot() const;
    bool rootIsSet() const;
    void unsetRoot();

    void setRoot(const std::shared_ptr<ComposeModelNode>& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    std::shared_ptr<ComposeModelNode> m_Root;
    bool m_RootIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CacheComposeModel_request_H_ */
