/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CachedModel.h
 *
 * Абстракция кэша модели/геометрии
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CachedModel_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CachedModel_H_


#include "c3dservice-api/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Абстракция кэша модели/геометрии
/// </summary>
class  CachedModel
    : public ModelBase
{
public:
    CachedModel();
    virtual ~CachedModel();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CachedModel members

    /// <summary>
    /// Путь (URL) к исходной модели/геометрии
    /// </summary>
    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();

    void setUrl(const utility::string_t& value);

    /// <summary>
    /// Статус генерации кэша
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const utility::string_t& value);

    /// <summary>
    /// Процент генерации кэша
    /// </summary>
    double getProgress() const;
    bool progressIsSet() const;
    void unsetProgress();

    void setProgress(double value);


protected:
    utility::string_t m_Url;
    bool m_UrlIsSet;
    utility::string_t m_Status;
    bool m_StatusIsSet;
    double m_Progress;
    bool m_ProgressIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CachedModel_H_ */
