/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetSessionsList_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetSessionsList_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetSessionsList_200_response_H_


#include "c3dservice-api/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  GetSessionsList_200_response
    : public ModelBase
{
public:
    GetSessionsList_200_response();
    virtual ~GetSessionsList_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GetSessionsList_200_response members

    /// <summary>
    /// Перечень активных пользователей
    /// </summary>
    std::vector<std::shared_ptr<utility::string_t>>& getUsers();
    bool usersIsSet() const;
    void unsetUsers();

    void setUsers(const std::vector<std::shared_ptr<utility::string_t>>& value);

    /// <summary>
    /// Перечень активных рабочих пространств
    /// </summary>
    std::vector<std::shared_ptr<utility::string_t>>& getWorkspaces();
    bool workspacesIsSet() const;
    void unsetWorkspaces();

    void setWorkspaces(const std::vector<std::shared_ptr<utility::string_t>>& value);


protected:
    std::vector<std::shared_ptr<utility::string_t>> m_Users;
    bool m_UsersIsSet;
    std::vector<std::shared_ptr<utility::string_t>> m_Workspaces;
    bool m_WorkspacesIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetSessionsList_200_response_H_ */
