/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RemoveModels_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveModels_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveModels_request_H_


#include "c3dservice-api/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  RemoveModels_request
    : public ModelBase
{
public:
    RemoveModels_request();
    virtual ~RemoveModels_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RemoveModels_request members

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getModels();
    bool modelsIsSet() const;
    void unsetModels();

    void setModels(const std::vector<utility::string_t>& value);


protected:
    std::vector<utility::string_t> m_Models;
    bool m_ModelsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RemoveModels_request_H_ */
