/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TreeNode.h
 *
 * Узел сборки модели
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TreeNode_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TreeNode_H_


#include "c3dservice-api/ModelBase.h"

#include "c3dservice-api/model/TreeNode.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Узел сборки модели
/// </summary>
class  TreeNode
    : public ModelBase
{
public:
    TreeNode();
    virtual ~TreeNode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TreeNode members

    /// <summary>
    /// Идентификатор узла
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// Атрибуты узла сборки
    /// </summary>
    std::map<utility::string_t, utility::string_t>& getAttrs();
    bool attrsIsSet() const;
    void unsetAttrs();

    void setAttrs(const std::map<utility::string_t, utility::string_t>& value);

    /// <summary>
    /// Дочерние узлы
    /// </summary>
    std::vector<std::shared_ptr<TreeNode>>& getChildren();
    bool childrenIsSet() const;
    void unsetChildren();

    void setChildren(const std::vector<std::shared_ptr<TreeNode>>& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    std::map<utility::string_t, utility::string_t> m_Attrs;
    bool m_AttrsIsSet;
    std::vector<std::shared_ptr<TreeNode>> m_Children;
    bool m_ChildrenIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TreeNode_H_ */
