/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Workspace.h
 *
 * Сессия рабочей области
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Workspace_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Workspace_H_


#include "c3dservice-api/ModelBase.h"

#include "c3dservice-api/model/Times.h"
#include <cpprest/details/basic_types.h>
#include <vector>
#include "c3dservice-api/model/Model.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Times;
class Model;

/// <summary>
/// Сессия рабочей области
/// </summary>
class  Workspace
    : public ModelBase
{
public:
    Workspace();
    virtual ~Workspace();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Workspace members

    /// <summary>
    /// Идентификатор
    /// </summary>
    utility::string_t getUuid() const;
    bool uuidIsSet() const;
    void unsetUuid();

    void setUuid(const utility::string_t& value);

    /// <summary>
    /// Является ли рабочая область демонстрационной
    /// </summary>
    bool isIsDemo() const;
    bool isDemoIsSet() const;
    void unsetIsDemo();

    void setIsDemo(bool value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Times> getTimes() const;
    bool timesIsSet() const;
    void unsetTimes();

    void setTimes(const std::shared_ptr<Times>& value);

    /// <summary>
    /// Перечень подключенных пользователей
    /// </summary>
    std::vector<std::shared_ptr<utility::string_t>>& getUsers();
    bool usersIsSet() const;
    void unsetUsers();

    void setUsers(const std::vector<std::shared_ptr<utility::string_t>>& value);

    /// <summary>
    /// Перечень используемых моделей
    /// </summary>
    std::vector<std::shared_ptr<Model>>& getModels();
    bool modelsIsSet() const;
    void unsetModels();

    void setModels(const std::vector<std::shared_ptr<Model>>& value);


protected:
    utility::string_t m_Uuid;
    bool m_UuidIsSet;
    bool m_IsDemo;
    bool m_IsDemoIsSet;
    std::shared_ptr<Times> m_Times;
    bool m_TimesIsSet;
    std::vector<std::shared_ptr<utility::string_t>> m_Users;
    bool m_UsersIsSet;
    std::vector<std::shared_ptr<Model>> m_Models;
    bool m_ModelsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Workspace_H_ */
