/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "c3dservice-api/model/CacheGeometry_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



CacheGeometry_request::CacheGeometry_request()
{
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_FileContentIsSet = false;
    m_Builder = utility::conversions::to_string_t("");
    m_BuilderIsSet = false;
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
}

CacheGeometry_request::~CacheGeometry_request()
{
}

void CacheGeometry_request::validate()
{
    // TODO: implement validation
}

web::json::value CacheGeometry_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UrlIsSet)
    {
        val[utility::conversions::to_string_t(U("url"))] = ModelBase::toJson(m_Url);
    }
    if(m_FileContentIsSet)
    {
        val[utility::conversions::to_string_t(U("fileContent"))] = ModelBase::toJson(m_FileContent);
    }
    if(m_BuilderIsSet)
    {
        val[utility::conversions::to_string_t(U("builder"))] = ModelBase::toJson(m_Builder);
    }
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }

    return val;
}

bool CacheGeometry_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("fileContent"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("fileContent")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFileContent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFileContent);
            setFileContent(refVal_setFileContent);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("builder"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("builder")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBuilder;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBuilder);
            setBuilder(refVal_setBuilder);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    return ok;
}

void CacheGeometry_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("url")), m_Url));
    }
    if(m_FileContentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("fileContent")), m_FileContent));
    }
    if(m_BuilderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("builder")), m_Builder));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
}

bool CacheGeometry_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("fileContent"))))
    {
        utility::string_t refVal_setFileContent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("fileContent"))), refVal_setFileContent );
        setFileContent(refVal_setFileContent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("builder"))))
    {
        utility::string_t refVal_setBuilder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("builder"))), refVal_setBuilder );
        setBuilder(refVal_setBuilder);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    return ok;
}

utility::string_t CacheGeometry_request::getUrl() const
{
    return m_Url;
}

void CacheGeometry_request::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool CacheGeometry_request::urlIsSet() const
{
    return m_UrlIsSet;
}

void CacheGeometry_request::unsetUrl()
{
    m_UrlIsSet = false;
}
utility::string_t CacheGeometry_request::getFileContent() const
{
    return m_FileContent;
}

void CacheGeometry_request::setFileContent(const utility::string_t& value)
{
    m_FileContent = value;
    m_FileContentIsSet = true;
}

bool CacheGeometry_request::fileContentIsSet() const
{
    return m_FileContentIsSet;
}

void CacheGeometry_request::unsetFileContent()
{
    m_FileContentIsSet = false;
}
utility::string_t CacheGeometry_request::getBuilder() const
{
    return m_Builder;
}

void CacheGeometry_request::setBuilder(const utility::string_t& value)
{
    m_Builder = value;
    m_BuilderIsSet = true;
}

bool CacheGeometry_request::builderIsSet() const
{
    return m_BuilderIsSet;
}

void CacheGeometry_request::unsetBuilder()
{
    m_BuilderIsSet = false;
}
utility::string_t CacheGeometry_request::getUuid() const
{
    return m_Uuid;
}

void CacheGeometry_request::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool CacheGeometry_request::uuidIsSet() const
{
    return m_UuidIsSet;
}

void CacheGeometry_request::unsetUuid()
{
    m_UuidIsSet = false;
}
}
}
}
}


