/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "c3dservice-api/model/CacheComposeModel_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



CacheComposeModel_request::CacheComposeModel_request()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_RootIsSet = false;
}

CacheComposeModel_request::~CacheComposeModel_request()
{
}

void CacheComposeModel_request::validate()
{
    // TODO: implement validation
}

web::json::value CacheComposeModel_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_RootIsSet)
    {
        val[utility::conversions::to_string_t(U("root"))] = ModelBase::toJson(m_Root);
    }

    return val;
}

bool CacheComposeModel_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("root"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("root")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ComposeModelNode> refVal_setRoot;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRoot);
            setRoot(refVal_setRoot);
        }
    }
    return ok;
}

void CacheComposeModel_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_RootIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("root")), m_Root));
    }
}

bool CacheComposeModel_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("root"))))
    {
        std::shared_ptr<ComposeModelNode> refVal_setRoot;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("root"))), refVal_setRoot );
        setRoot(refVal_setRoot);
    }
    return ok;
}

utility::string_t CacheComposeModel_request::getUuid() const
{
    return m_Uuid;
}

void CacheComposeModel_request::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool CacheComposeModel_request::uuidIsSet() const
{
    return m_UuidIsSet;
}

void CacheComposeModel_request::unsetUuid()
{
    m_UuidIsSet = false;
}
std::shared_ptr<ComposeModelNode> CacheComposeModel_request::getRoot() const
{
    return m_Root;
}

void CacheComposeModel_request::setRoot(const std::shared_ptr<ComposeModelNode>& value)
{
    m_Root = value;
    m_RootIsSet = true;
}

bool CacheComposeModel_request::rootIsSet() const
{
    return m_RootIsSet;
}

void CacheComposeModel_request::unsetRoot()
{
    m_RootIsSet = false;
}
}
}
}
}


