/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "c3dservice-api/model/RemoveModels_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



RemoveModels_request::RemoveModels_request()
{
    m_ModelsIsSet = false;
}

RemoveModels_request::~RemoveModels_request()
{
}

void RemoveModels_request::validate()
{
    // TODO: implement validation
}

web::json::value RemoveModels_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ModelsIsSet)
    {
        val[utility::conversions::to_string_t(U("models"))] = ModelBase::toJson(m_Models);
    }

    return val;
}

bool RemoveModels_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("models"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("models")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setModels;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModels);
            setModels(refVal_setModels);
        }
    }
    return ok;
}

void RemoveModels_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ModelsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("models")), m_Models));
    }
}

bool RemoveModels_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("models"))))
    {
        std::vector<utility::string_t> refVal_setModels;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("models"))), refVal_setModels );
        setModels(refVal_setModels);
    }
    return ok;
}

std::vector<utility::string_t>& RemoveModels_request::getModels()
{
    return m_Models;
}

void RemoveModels_request::setModels(const std::vector<utility::string_t>& value)
{
    m_Models = value;
    m_ModelsIsSet = true;
}

bool RemoveModels_request::modelsIsSet() const
{
    return m_ModelsIsSet;
}

void RemoveModels_request::unsetModels()
{
    m_ModelsIsSet = false;
}
}
}
}
}


