/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "c3dservice-api/model/TreeNode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



TreeNode::TreeNode()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_AttrsIsSet = false;
    m_ChildrenIsSet = false;
}

TreeNode::~TreeNode()
{
}

void TreeNode::validate()
{
    // TODO: implement validation
}

web::json::value TreeNode::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_AttrsIsSet)
    {
        val[utility::conversions::to_string_t(U("attrs"))] = ModelBase::toJson(m_Attrs);
    }
    if(m_ChildrenIsSet)
    {
        val[utility::conversions::to_string_t(U("children"))] = ModelBase::toJson(m_Children);
    }

    return val;
}

bool TreeNode::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("attrs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("attrs")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, utility::string_t> refVal_setAttrs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAttrs);
            setAttrs(refVal_setAttrs);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("children"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("children")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<TreeNode>> refVal_setChildren;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChildren);
            setChildren(refVal_setChildren);
        }
    }
    return ok;
}

void TreeNode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_AttrsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("attrs")), m_Attrs));
    }
    if(m_ChildrenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("children")), m_Children));
    }
}

bool TreeNode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("attrs"))))
    {
        std::map<utility::string_t, utility::string_t> refVal_setAttrs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("attrs"))), refVal_setAttrs );
        setAttrs(refVal_setAttrs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("children"))))
    {
        std::vector<std::shared_ptr<TreeNode>> refVal_setChildren;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("children"))), refVal_setChildren );
        setChildren(refVal_setChildren);
    }
    return ok;
}

utility::string_t TreeNode::getUuid() const
{
    return m_Uuid;
}

void TreeNode::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool TreeNode::uuidIsSet() const
{
    return m_UuidIsSet;
}

void TreeNode::unsetUuid()
{
    m_UuidIsSet = false;
}
std::map<utility::string_t, utility::string_t>& TreeNode::getAttrs()
{
    return m_Attrs;
}

void TreeNode::setAttrs(const std::map<utility::string_t, utility::string_t>& value)
{
    m_Attrs = value;
    m_AttrsIsSet = true;
}

bool TreeNode::attrsIsSet() const
{
    return m_AttrsIsSet;
}

void TreeNode::unsetAttrs()
{
    m_AttrsIsSet = false;
}
std::vector<std::shared_ptr<TreeNode>>& TreeNode::getChildren()
{
    return m_Children;
}

void TreeNode::setChildren(const std::vector<std::shared_ptr<TreeNode>>& value)
{
    m_Children = value;
    m_ChildrenIsSet = true;
}

bool TreeNode::childrenIsSet() const
{
    return m_ChildrenIsSet;
}

void TreeNode::unsetChildren()
{
    m_ChildrenIsSet = false;
}
}
}
}
}


