/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "c3dservice-api/model/Workspace.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Workspace::Workspace()
{
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_IsDemo = false;
    m_IsDemoIsSet = false;
    m_TimesIsSet = false;
    m_UsersIsSet = false;
    m_ModelsIsSet = false;
}

Workspace::~Workspace()
{
}

void Workspace::validate()
{
    // TODO: implement validation
}

web::json::value Workspace::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_IsDemoIsSet)
    {
        val[utility::conversions::to_string_t(U("isDemo"))] = ModelBase::toJson(m_IsDemo);
    }
    if(m_TimesIsSet)
    {
        val[utility::conversions::to_string_t(U("times"))] = ModelBase::toJson(m_Times);
    }
    if(m_UsersIsSet)
    {
        val[utility::conversions::to_string_t(U("users"))] = ModelBase::toJson(m_Users);
    }
    if(m_ModelsIsSet)
    {
        val[utility::conversions::to_string_t(U("models"))] = ModelBase::toJson(m_Models);
    }

    return val;
}

bool Workspace::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("isDemo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("isDemo")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsDemo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsDemo);
            setIsDemo(refVal_setIsDemo);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("times"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("times")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Times> refVal_setTimes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimes);
            setTimes(refVal_setTimes);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("users"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("users")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<utility::string_t>> refVal_setUsers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsers);
            setUsers(refVal_setUsers);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("models"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("models")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Model>> refVal_setModels;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModels);
            setModels(refVal_setModels);
        }
    }
    return ok;
}

void Workspace::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_IsDemoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("isDemo")), m_IsDemo));
    }
    if(m_TimesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("times")), m_Times));
    }
    if(m_UsersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("users")), m_Users));
    }
    if(m_ModelsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("models")), m_Models));
    }
}

bool Workspace::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("isDemo"))))
    {
        bool refVal_setIsDemo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("isDemo"))), refVal_setIsDemo );
        setIsDemo(refVal_setIsDemo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("times"))))
    {
        std::shared_ptr<Times> refVal_setTimes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("times"))), refVal_setTimes );
        setTimes(refVal_setTimes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("users"))))
    {
        std::vector<std::shared_ptr<utility::string_t>> refVal_setUsers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("users"))), refVal_setUsers );
        setUsers(refVal_setUsers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("models"))))
    {
        std::vector<std::shared_ptr<Model>> refVal_setModels;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("models"))), refVal_setModels );
        setModels(refVal_setModels);
    }
    return ok;
}

utility::string_t Workspace::getUuid() const
{
    return m_Uuid;
}

void Workspace::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool Workspace::uuidIsSet() const
{
    return m_UuidIsSet;
}

void Workspace::unsetUuid()
{
    m_UuidIsSet = false;
}
bool Workspace::isIsDemo() const
{
    return m_IsDemo;
}

void Workspace::setIsDemo(bool value)
{
    m_IsDemo = value;
    m_IsDemoIsSet = true;
}

bool Workspace::isDemoIsSet() const
{
    return m_IsDemoIsSet;
}

void Workspace::unsetIsDemo()
{
    m_IsDemoIsSet = false;
}
std::shared_ptr<Times> Workspace::getTimes() const
{
    return m_Times;
}

void Workspace::setTimes(const std::shared_ptr<Times>& value)
{
    m_Times = value;
    m_TimesIsSet = true;
}

bool Workspace::timesIsSet() const
{
    return m_TimesIsSet;
}

void Workspace::unsetTimes()
{
    m_TimesIsSet = false;
}
std::vector<std::shared_ptr<utility::string_t>>& Workspace::getUsers()
{
    return m_Users;
}

void Workspace::setUsers(const std::vector<std::shared_ptr<utility::string_t>>& value)
{
    m_Users = value;
    m_UsersIsSet = true;
}

bool Workspace::usersIsSet() const
{
    return m_UsersIsSet;
}

void Workspace::unsetUsers()
{
    m_UsersIsSet = false;
}
std::vector<std::shared_ptr<Model>>& Workspace::getModels()
{
    return m_Models;
}

void Workspace::setModels(const std::vector<std::shared_ptr<Model>>& value)
{
    m_Models = value;
    m_ModelsIsSet = true;
}

bool Workspace::modelsIsSet() const
{
    return m_ModelsIsSet;
}

void Workspace::unsetModels()
{
    m_ModelsIsSet = false;
}
}
}
}
}


