/**
 * OpenAPI C3D-Service
 * Open API спецификация к REST API микросервиса C3D Web Vision.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: info@c3dlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MonitorApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MonitorApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MonitorApi_H_



#include "c3dservice-api/ApiClient.h"
#include "c3dservice-api/ModelBase.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MonitorApi 
{
public:

    explicit MonitorApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MonitorApi();

    /// <summary>
    /// Запросить информацию о состоянии сервиса
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<void> getStatus(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MonitorApi_H_ */

